version: '3.6'

services:
  ewsposter:
    container_name: ewsposter
    restart: always
    build:
      context: .
      args:
        - VERSION=${VERSION}
        - TITLE=${NAME}
        - AUTHOR=${AUTHOR}
        - DESCRIPTION=${DESCRIPTION}
        - LICENSES=${LICENSES}
        - URL=${URL}
        - CREATED=${CREATED}
        - REVISION=${REVISION}
      tags:
        - mtr.devops.telekom.de/markus_schroer/${NAME}:${VERSION}
        - mtr.devops.telekom.de/markus_schroer/${NAME}:latest
    networks:
      - ewsposter_local
    environment:
      - EWS_HPFEEDS_ENABLE=${HPF_ENABLE}
      - EWS_HPFEEDS_HOST=${HPF_HOST}
      - EWS_HPFEEDS_PORT=${HPF_PORT}
      - EWS_HPFEEDS_CHANNELS=${HPF_CHANNELS}
      - EWS_HPFEEDS_IDENT=${HPF_IDENT}
      - EWS_HPFEEDS_SECRET=${HPF_SECRET}
      - EWS_HPFEEDS_TLSCERT=${HPF_TLSCERT}
      - EWS_HPFEEDS_FORMAT=${HPF_FORMAT}
    image: ${USERNAME}/${NAME}:${VERSION}
    volumes:
      - /data:/data
      - /data/ews/config/ews.ip:/opt/ewsposter/ews.ip
      - /data/ews/config/ews.cfg:/opt/ewsposter/ews.cfg
      - /data/ews/log:/opt/ewsposter/log

networks:
  ewsposter_local:
